observatories = [
    {
        "name": "George Mason Univ. Observatory, Virginia",
        "latitude": 38.8282,
        "longitude": -77.3053,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Bowling Green State Univ. Observatory, Ohio",
        "latitude": 41.378333,
        "longitude": -83.659167,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Collins Observatory, Colby College, Maine",
        "latitude": 44.56667,
        "longitude": -69.656378,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Smith College Observatory, Northampton, MA",
        "latitude": 42.317036,
        "longitude": -72.639514,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Moore Observatory, Univ. of Louisville, Kentucky",
        "latitude": 38.344792,
        "longitude": -85.528475,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Harvard Clay Telescope, Cambridge, MA",
        "latitude": 42.3766,
        "longitude": -71.1169,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Oak Ridge Observatory, Harvard, MA",
        "latitude": 42.505261,
        "longitude": -71.558144,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Leander McCormick Observatory, Univ. of Virginia",
        "latitude": 38.033333,
        "longitude": -78.523333,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Black Moshannon Observatory, State College PA",
        "latitude": 40.921667,
        "longitude": -78.005000,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Michael L. Britton Observatory, Dickinson College, PA",
        "latitude": 40.20398,
        "longitude": -77.19786,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Fan Mountain Observatory, VA",
        "latitude": 37.878333,
        "longitude": -78.693333,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Whitin Observatory, Wellesley College, MA",
        "latitude": 42.295000,
        "longitude": -71.305833,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Olin Observatory, Connecticut College, CT",
        "latitude": 41.378889,
        "longitude": -72.105278,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Sperry Observatory, Union County College, NJ",
        "latitude": 40.66632,
        "longitude": -74.32327,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Peter van de Kamp Observatory, Swarthmore College, PA",
        "latitude": 39.907100,
        "longitude": -75.355550,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Union College Observatory, NY",
        "latitude": 42.8176,
        "longitude": -73.9283,
        "timezone": "EST5EDT",
    },
    {
        "name": "Van Vleck Observatory, Wesleyan University, CT",
        "latitude": 41.555000,
        "longitude": -72.659167,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Vassar College Observatory, Poughkeepsie, NY",
        "latitude": 41.683011,
        "longitude": -73.890604,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Williams College Observatory, MA",
        "latitude": 42.7115,
        "longitude": -73.2052,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Mittelman Observatory, Middlebury College, VT",
        "latitude": 44.0134,
        "longitude": -73.1813,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "George R. Wallace, Jr. Astrophysical Observatory, MA",
        "latitude": 42.295,
        "longitude": -71.485,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Foggy Bottom Observatory, Colgate Univ., NY",
        "latitude": 42.81651,
        "longitude": -75.532568,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Breyo Observatory, Siena College, NY",
        "latitude": 42.719546,
        "longitude": -73.751433,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "C.E.K. Mees Observatory, Univ. Rochester, NY",
        "latitude": 42.7002778,
        "longitude": -77.4087667,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
    },
    {
        "name": "Observatoire du Mont-Mégantic, Québec",
        "latitude": 45.455683,
        "longitude": -71.1521,
        "timezone_integer": 5,
        "timezone": "America/Toronto",
    },
    {
        "name": "Kitt Peak National Observatory",
        "latitude": 31.963333,
        "longitude": -111.600000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Mount Lemmon",
        "latitude": 32.416667,
        "longitude": -110.731667,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "MMT Observatory",
        "latitude": 31.688333,
        "longitude": -110.885000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Lowell Observatory",
        "latitude": 35.096667,
        "longitude": -111.535000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Whipple Observatory",
        "latitude": 31.680944,
        "longitude": -110.877500,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Mount Graham Observatory",
        "latitude": 32.701667,
        "longitude": -109.891667,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Winer Observatory",
        "latitude": 31.665583,
        "longitude": -110.60178,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
    },
    {
        "name": "Apache Point Observatory",
        "latitude": 32.780000,
        "longitude": -105.820000,
        "timezone_integer": 7,
        "timezone": "MST7MDT",
    },
    {
        "name": "Mauna Kea (Keck, Gemini, CFHT, Subaru, IRTF, etc.)",
        "latitude": 19.828333,
        "longitude": -155.478333,
        "timezone_integer": 10,
        "timezone": "Pacific/Honolulu",
    },
    {
        "name": "Dominion Astrophysical Observatory",
        "latitude": 48.521667,
        "longitude": -123.416667,
        "timezone_integer": 8,
        "timezone": "America/Vancouver",
    },
    {
        "name": "Lick Observatory",
        "latitude": 37.343333,
        "longitude": -121.636667,
        "timezone_integer": 8,
        "timezone": "PST8PDT",
    },
    {
        "name": "McDonald Observatory",
        "latitude": 30.671667,
        "longitude": -104.021667,
        "timezone_integer": 6,
        "timezone": "CST6CDT",
    },
    {
        "name": "Observatorio Astronomico Nacional, San Pedro Martir",
        "latitude": 31.029167,
        "longitude": -115.486944,
        "timezone_integer": 7,
        "timezone": "America/Tijuana",
    },
    {
        "name": "Observatorio Astronomico Nacional, Tonantzintla",
        "latitude": 19.032778,
        "longitude": -98.313889,
        "timezone_integer": 8,
        "timezone": "America/Mexico_City",
    },
    {
        "name": "Palomar Observatory",
        "latitude": 33.356000,
        "longitude": -116.863000,
        "timezone_integer": 8,
        "timezone": "PST8PDT",
    },
    {
        "name": "Red Buttes Observatory, Wyoming",
        "latitude": 41.17642,
        "longitude": -105.57403,
        "timezone": "MST7MDT",
    },
    {
        "name": "Wyoming Infrared Observatory (WIRO)",
        "latitude": 41.09706,
        "longitude": -105.97653,
        "timezone": "MST7MDT",
    },
    {
        "name": "Boyce-Astro Research Observatory (San Diego)",
        "latitude": 32.6133,
        "longitude": -116.3319,
        "timezone": "America/Los_Angeles",
    },
    {
        "name": "Rothney Astrophysical Observatory (Calgary)",
        "latitude": 50.868039,
        "longitude": -114.291142,
        "timezone": "America/Edmonton",
    },
    {
        "name": "New Mexico Skies, Mayhill, NM",
        "latitude": 32.90388889,
        "longitude": -105.52888889,
        "timezone_integer": 7,
        "timezone": "MST7MDT",
    },
    {
        "name": "Sierra Remote Observatories, CA",
        "latitude": 37.07055,
        "longitude": -119.4128,
        "timezone": "America/Los_Angeles",
    },
    {
        "name": "Table Mountain Observatory, CA",
        "latitude": 34.38139,
        "longitude": -117.68194,
        "timezone": "America/Los_Angeles",
    },
    {
        "name": "Sommers-Bausch Observatory, Univ. of Colorado",
        "latitude": 40.00371,
        "longitude": -105.2630,
        "timezone": "America/Denver",
    },
    {
        "name": "Maury Lewin Astronomical Observatory",
        "latitude": 34.142075,
        "longitude": -117.872065,
        "timezone": "America/Los_Angeles",
    },
    {
        "name": "Cerro Tololo Interamerican Observatory",
        "latitude": -30.165278,
        "longitude": -70.815000,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "Gemini South Observatory",
        "latitude": -30.240750,
        "longitude": -70.736693,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "European Southern Observatory: La Silla",
        "latitude": -29.256667,
        "longitude": -70.730000,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "European Southern Observatory: Paranal",
        "latitude": -24.625000,
        "longitude": -70.403333,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "ALMA",
        "latitude": -23.029,
        "longitude": -67.755,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "Las Campanas Observatory",
        "latitude": -29.003333,
        "longitude": -70.701667,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
    },
    {
        "name": "Observatorio Astronomico de La Plata, Buenos Aires",
        "latitude": -34.906751,
        "longitude": -57.932299,
        "timezone_integer": 3,
        "timezone": "America/Argentina/Buenos_Aires",
    },
    {
        "name": "Estacion Astrofisica Bosque Alegre, Cordoba, Argentina",
        "latitude": -31.598333,
        "longitude": -64.545833,
        "timezone_integer": 3,
        "timezone": "America/Argentina/Cordoba",
    },
    {
        "name": "National Observatory of Venezuela",
        "latitude": 8.790000,
        "longitude": -70.866667,
        "timezone_integer": 4,
        "timezone": "America/Caracas",
    },
    {
        "name": "Laboratorio Nacional de Astrofisica, Brazil",
        "latitude": -22.534444,
        "longitude": -45.582500,
        "timezone_integer": 3,
        "timezone": "America/Sao_Paulo",
    },
    {
        "name": "Complejo Astronomico El Leoncito, San Juan, Argentina",
        "latitude": -31.799167,
        "longitude": -69.295000,
        "timezone_integer": 3,
        "timezone": "America/Argentina/San_Juan",
    },
    {
        "name": "Mt. Stromlo Observatory",
        "latitude": -35.320650,
        "longitude": 149.0081,
        "timezone_integer": -10,
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Mt. Kent Observatory",
        "latitude": -27.797861,
        "longitude": 151.855417,
        "timezone": "Australia/Brisbane",
    },
    {
        "name": "Anglo-Australian Observatory / Siding Spring",
        "latitude": -31.274,
        "longitude": 149.069,
        "timezone_integer": -10,
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Mount John University Observatory, New Zealand",
        "latitude": -43.986667,
        "longitude": 170.465,
        "timezone_integer": -12,
        "timezone": "Pacific/Auckland",
    },
    {
        "name": "Roque de los Muchachos, La Palma",
        "latitude": 28.758333,
        "longitude": -17.880000,
        "timezone_integer": 0,
        "timezone": "Atlantic/Canary",
    },
    {
        "name": "Observatorio Terrassa, Spain",
        "latitude": 41.571578,
        "longitude": 2.0349,
        "timezone_integer": -1,
        "timezone": "Europe/Madrid",
    },
    {
        "name": "Observatorio de Sierra Nevada, Spain",
        "latitude": 37.064167,
        "longitude": -3.384722,
        "timezone_integer": -1,
        "timezone": "Europe/Madrid",
    },
    {
        "name": "SLN - Catania Astrophysical Observatory, Italy",
        "latitude": 37.691667,
        "longitude": -345.026667,
        "timezone_integer": -1,
        "timezone": "Europe/Rome",
    },
    {
        "name": "Mt. Ekar Observatory, Asiago, Italy",
        "latitude": 45.848589,
        "longitude": -348.418867,
        "timezone_integer": -1,
        "timezone": "Europe/Rome",
    },
    {
        "name": "Ege University Observatory, Izmir, Turkey",
        "latitude": 38.398333,
        "longitude": 27.275000,
        "timezone_integer": 2,
        "timezone": "Europe/Istanbul",
    },
    {
        "name": "Tubitak National Observatory, Turkey",
        "latitude": 36.825000,
        "longitude": 30.333333,
        "timezone_integer": -2,
        "timezone": "Europe/Istanbul",
    },
    {
        "name": "National Astronomical Observatory Rozhen - Bulgaria",
        "latitude": 41.693056,
        "longitude": -335.256111,
        "timezone_integer": -2,
        "timezone": "Europe/Sofia",
    },
    {
        "name": "Calar Alto Observatory, Spain",
        "latitude": 37.223611,
        "longitude": -2.546250,
        "timezone_integer": -1,
        "timezone": "Europe/Madrid",
    },
    {
        "name": "Observatorium Hoher List (Universität Bonn) - Germany",
        "latitude": 50.162760,
        "longitude": 6.850000,
        "timezone_integer": -1,
        "timezone": "Europe/Berlin",
    },
    {
        "name": "Boyden Observatory, Bloemfontein, South Africa",
        "latitude": -29.038889,
        "longitude": -332.594444,
        "timezone_integer": -2,
        "timezone": "Africa/Johannesburg",
    },
    {
        "name": "South African Astronomical Observatory",
        "latitude": -32.379444,
        "longitude": -339.189306,
        "timezone_integer": -2,
        "timezone": "Africa/Johannesburg",
    },
    {
        "name": "Beijing XingLong Observatory, China",
        "latitude": 40.393333,
        "longitude": -242.425000,
        "timezone_integer": -8,
        "timezone": "Asia/Shanghai",
    },
    {
        "name": "Vainu Bappu Observatory, India",
        "latitude": 12.576660,
        "longitude": -281.173400,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
    },
    {
        "name": "Indian Astronomical Observatory, Hanle",
        "latitude": 32.779400,
        "longitude": -281.035830,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
    },
    {
        "name": "Aryabhatta Research Institute, India",
        "latitude": 29.360000,
        "longitude": -280.543610,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
    },
]
