# Generated by Django 5.1 on 2024-08-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_script_program_alter_script_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='command',
            field=models.CharField(blank=True, help_text='Advanced: raw command to run', max_length=100, null=True),
        ),
    ]
