observatoryInitList = [
    {
        "name": "George Mason Univ. Observatory, Virginia",
        "latitude": 38.8282,
        "longitude": -77.3053,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.8128, 
        "elevation": 135,
        "light_pollution": 13,
    },
    {
        "name": "Bowling Green State Univ. Observatory, Ohio",
        "latitude": 41.378333,
        "longitude": -83.659167,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.5,
        "elevation": 215,
        "light_pollution": 11,
    },
    {
        "name": "Collins Observatory, Colby College, Maine",
        "latitude": 44.56667,
        "longitude": -69.656378,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.7,
        "elevation": 65,
        "light_pollution": 9,
    },
    {
        "name": "Smith College Observatory, Northampton, MA",
        "latitude": 42.317036,
        "longitude": -72.639514,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.4064,
        "elevation": 63,
        "light_pollution": 10,
    },
    {
        "name": "Moore Observatory, Univ. of Louisville, Kentucky",
        "latitude": 38.344792,
        "longitude": -85.528475,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6,
        "elevation": 220,
        "light_pollution": 12,
    },
    {
        "name": "Harvard Clay Telescope, Cambridge, MA",
        "latitude": 42.3766,
        "longitude": -71.1169,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.4064,
        "elevation": 17,
        "light_pollution": 14,
    },
    {
        "name": "Leander McCormick Observatory, Univ. of Virginia",
        "latitude": 38.033333,
        "longitude": -78.523333,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6604,
        "elevation": 252,
        "light_pollution": 10,
    },
    {
        "name": "Michael L. Britton Observatory, Dickinson College, PA",
        "latitude": 40.20398,
        "longitude": -77.19786,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 148,
        "light_pollution": 11,
    },
    {
        "name": "Fan Mountain Observatory, VA",
        "latitude": 37.878333,
        "longitude": -78.693333,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6604,
        "elevation": 553,
        "light_pollution": 11,
    },
    {
        "name": "Whitin Observatory, Wellesley College, MA",
        "latitude": 42.295000,
        "longitude": -71.305833,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 43,
        "light_pollution": 7,
    },
    {
        "name": "Olin Observatory, Connecticut College, CT",
        "latitude": 41.378889,
        "longitude": -72.105278,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.508,
        "elevation": 65,
        "light_pollution": 11,
    },
    {
        "name": "Sperry Observatory, Union County College, NJ",
        "latitude": 40.66632,
        "longitude": -74.32327,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 23,
        "light_pollution": 11,
    },
    {
        "name": "Peter van de Kamp Observatory, Swarthmore College, PA",
        "latitude": 39.907100,
        "longitude": -75.355550,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 71,
        "light_pollution": 12,
    },
    {
        "name": "Union College Observatory, NY",
        "latitude": 42.8176,
        "longitude": -73.9283,
        "timezone": "EST5EDT",
        "diameter": 0.508,
        "elevation": 92,
        "light_pollution": 11,
    },
    {
        "name": "Van Vleck Observatory, Wesleyan University, CT",
        "latitude": 41.555000,
        "longitude": -72.659167,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 62,
        "light_pollution": 11,
    },
    {
        "name": "Vassar College Observatory, Poughkeepsie, NY",
        "latitude": 41.683011,
        "longitude": -73.890604,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.8128,
        "elevation": 60,
        "light_pollution": 11,
    },
    {
        "name": "Williams College Observatory, MA",
        "latitude": 42.7115,
        "longitude": -73.2052,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 222,
        "light_pollution": 8,
    },
    {
        "name": "Mittelman Observatory, Middlebury College, VT",
        "latitude": 44.0134,
        "longitude": -73.1813,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 122,
        "light_pollution": 8,
    },
    {
        "name": "George R. Wallace, Jr. Astrophysical Observatory, MA",
        "latitude": 42.295,
        "longitude": -71.485,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 91,
        "light_pollution": 12,
    },
    {
        "name": "Foggy Bottom Observatory, Colgate Univ., NY",
        "latitude": 42.81651,
        "longitude": -75.532568,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.4064,
        "elevation": 410,
        "light_pollution": 8,
    },
    {
        "name": "Breyo Observatory, Siena College, NY",
        "latitude": 42.719546,
        "longitude": -73.751433,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.7,
        "elevation": 97,
        "light_pollution": 14,
    },
    {
        "name": "C.E.K. Mees Observatory, Univ. Rochester, NY",
        "latitude": 42.7002778,
        "longitude": -77.4087667,
        "timezone_integer": 5,
        "timezone": "EST5EDT",
        "diameter": 0.6096,
        "elevation": 690,
        "light_pollution": 7,
    },
    {
        "name": "Observatoire du Mont-Mégantic, Québec",
        "latitude": 45.455683,
        "longitude": -71.1521,
        "timezone_integer": 5,
        "timezone": "America/Toronto",
        "diameter": 1.6,
        "elevation": 1089,
        "light_pollution": 5,
    },
    {
        "name": "Kitt Peak National Observatory",
        "latitude": 31.963333,
        "longitude": -111.600000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 4,
        "elevation": 2120,
        "light_pollution": 3,
    },
    {
        "name": "Mount Lemmon",
        "latitude": 32.416667,
        "longitude": -110.731667,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 1.52,
        "elevation": 2510,
        "light_pollution": 7,
    },
    {
        "name": "MMT Observatory",
        "latitude": 31.688333,
        "longitude": -110.885000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 6.5,
        "elevation": 2608,
        "light_pollution": 3,
    },
    {
        "name": "Lowell Observatory",
        "latitude": 35.096667,
        "longitude": -111.535000,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 4.3,
        "elevation": 2198,
        "light_pollution": 5,
    },
    {
        "name": "Whipple Observatory",
        "latitude": 31.680944,
        "longitude": -110.877500,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 4.7,
        "elevation": 2320,
        "light_pollution": 5,
    },
    {
        "name": "Mount Graham Observatory",
        "latitude": 32.701667,
        "longitude": -109.891667,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 11.9,
        "elevation": 2902,
        "light_pollution": 3,
    },
    {
        "name": "Winer Observatory",
        "latitude": 31.665583,
        "longitude": -110.60178,
        "timezone_integer": 7,
        "timezone": "America/Phoenix",
        "diameter": 0.7,
        "elevation": 1503,
        "light_pollution": 5,
    },
    {
        "name": "Apache Point Observatory",
        "latitude": 32.780000,
        "longitude": -105.820000,
        "timezone_integer": 7,
        "timezone": "MST7MDT",
        "diameter": 3.48,
        "elevation": 2798,
        "light_pollution": 2,
    },
    {
        "name": "Mauna Kea (Keck, Gemini, CFHT, Subaru, IRTF, etc.)",
        "latitude": 19.828333,
        "longitude": -155.478333,
        "timezone_integer": 10,
        "timezone": "Pacific/Honolulu",
        "diameter": 10,
        "elevation": 4213,
        "light_pollution": 1,
    },
    {
        "name": "Dominion Astrophysical Observatory",
        "latitude": 48.521667,
        "longitude": -123.416667,
        "timezone_integer": 8,
        "timezone": "America/Vancouver",
        "diameter": 1.85,
        "elevation": 229,
        "light_pollution": 9,
    },
    {
        "name": "Lick Observatory",
        "latitude": 37.343333,
        "longitude": -121.636667,
        "timezone_integer": 8,
        "timezone": "PST8PDT",
        "diameter": 3.05,
        "elevation": 1290,
        "light_pollution": 8,
    },
    {
        "name": "McDonald Observatory",
        "latitude": 30.671667,
        "longitude": -104.021667,
        "timezone_integer": 6,
        "timezone": "CST6CDT",
        "diameter": 10,
        "elevation": 2075,
        "light_pollution": 2,
    },
    {
        "name": "Observatorio Astronomico Nacional, San Pedro Martir",
        "latitude": 31.029167,
        "longitude": -115.486944,
        "timezone_integer": 7,
        "timezone": "America/Tijuana",
        "diameter": 2.1,
        "elevation": 2830,
        "light_pollution": 1,
    },
    {
        "name": "Observatorio Astronomico Nacional, Tonantzintla",
        "latitude": 19.032778,
        "longitude": -98.313889,
        "timezone_integer": 8,
        "timezone": "America/Mexico_City",
        "diameter": 0.7,
        "elevation": 2174,
        "light_pollution": 12,
    },
    {
        "name": "Palomar Observatory",
        "latitude": 33.356000,
        "longitude": -116.863000,
        "timezone_integer": 8,
        "timezone": "PST8PDT",
        "diameter": 5.08,
        "elevation": 1706,
        "light_pollution": 7,
    },
    {
        "name": "Red Buttes Observatory, Wyoming",
        "latitude": 41.17642,
        "longitude": -105.57403,
        "timezone": "MST7MDT",
        "diameter": 0.6,
        "elevation": 2249,
        "light_pollution": 7,
    },
    {
        "name": "Wyoming Infrared Observatory (WIRO)",
        "latitude": 41.09706,
        "longitude": -105.97653,
        "timezone": "MST7MDT",
        "diameter": 0.6,
        "elevation": 2919,
        "light_pollution": 5,
    },
    {
        "name": "Boyce-Astro Research Observatory (San Diego)",
        "latitude": 32.6133,
        "longitude": -116.3319,
        "timezone": "America/Los_Angeles",
        "diameter": 0.4318,
        "elevation": 1133,
        "light_pollution": 7,
    },
    {
        "name": "Rothney Astrophysical Observatory (Calgary)",
        "latitude": 50.868039,
        "longitude": -114.291142,
        "timezone": "America/Edmonton",
        "diameter": 1.83,
        "elevation": 1271,
        "light_pollution": 10,
    },
    {
        "name": "New Mexico Skies, Mayhill, NM",
        "latitude": 32.90388889,
        "longitude": -105.52888889,
        "timezone_integer": 7,
        "timezone": "MST7MDT",
        "diameter": 0.51,
        "elevation": 2214,
        "light_pollution": 7,
    },
    {
        "name": "Sierra Remote Observatories, CA",
        "latitude": 37.07055,
        "longitude": -119.4128,
        "timezone": "America/Los_Angeles",
        "diameter": 0.4064,
        "elevation": 1404,
        "light_pollution": 5,
    },
    {
        "name": "Table Mountain Observatory, CA",
        "latitude": 34.38139,
        "longitude": -117.68194,
        "timezone": "America/Los_Angeles",
        "diameter": 1.016,
        "elevation": 2292,
        "light_pollution": 6,
    },
    {
        "name": "Griffith Observatory, CA",
        "latitude": 34.11833,
        "longitude": -118.20033,
        "timezone": "America/Los_Angeles",
        "diameter": 0.3048,
        "elevation": 346,
        "light_pollution": 14,
    },
    {
        "name": "Las Cumbres Observatory, CA",
        "latitude": 34.4327,
        "longitude": -119.8630,
        "timezone": "America/Los_Angeles",
        "diameter": 2,
        "elevation": 2163,
        "light_pollution": 10,
    },
    {
        "name": "Sommers-Bausch Observatory, Univ. of Colorado",
        "latitude": 40.00371,
        "longitude": -105.2630,
        "timezone": "America/Denver",
        "diameter": 0.508,
        "elevation": 1647,
        "light_pollution": 8,
    },
    {
        "name": "Maury Lewin Astronomical Observatory",
        "latitude": 34.142075,
        "longitude": -117.872065,
        "timezone": "America/Los_Angeles",
        "diameter": 0.356,
        "elevation": 233,
        "light_pollution": 13,
    },
    {
        "name": "Cerro Tololo Interamerican Observatory",
        "latitude": -30.165278,
        "longitude": -70.815000,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 1.5,
        "elevation": 2215,
        "light_pollution": 3,
    },
    {
        "name": "Gemini South Observatory",
        "latitude": -30.240750,
        "longitude": -70.736693,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 8.1,
        "elevation": 2750,
        "light_pollution": 2,
    },
    {
        "name": "European Southern Observatory: La Silla",
        "latitude": -29.256667,
        "longitude": -70.730000,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 3.57,
        "elevation": 2332,
        "light_pollution": 1,
    },
    {
        "name": "European Southern Observatory: Paranal",
        "latitude": -24.625000,
        "longitude": -70.403333,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 8.2,
        "elevation": 2635,
        "light_pollution": 0,
    },
    {
        "name": "ALMA",
        "latitude": -23.029,
        "longitude": -67.755,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 6.5,
        "elevation": 5035,
        "light_pollution": 2,
    },
    {
        "name": "Las Campanas Observatory",
        "latitude": -29.003333,
        "longitude": -70.701667,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 6.5,
        "elevation": 2282,
        "light_pollution": 1,
    },
    {
        "name": "Vera C. Rubin Observatory",
        "latitude": -30.244639,
        "longitude": -70.749417,
        "timezone_integer": 4,
        "timezone": "America/Santiago",
        "diameter": 8.4,
        "elevation": 2663,
        "light_pollution": 2,
    },
    {
        "name": "Observatorio Astronomico de La Plata, Buenos Aires",
        "latitude": -34.906751,
        "longitude": -57.932299,
        "timezone_integer": 3,
        "timezone": "America/Argentina/Buenos_Aires",
        "diameter": 2.15,
        "elevation": 26,
        "light_pollution": 14,
    },
    {
        "name": "Estacion Astrofisica Bosque Alegre, Cordoba, Argentina",
        "latitude": -31.598333,
        "longitude": -64.545833,
        "timezone_integer": 3,
        "timezone": "America/Argentina/Cordoba",
        "diameter": 1.54,
        "elevation": 1156,
        "light_pollution": 5,
    },
    {
        "name": "National Observatory of Venezuela",
        "latitude": 8.790000,
        "longitude": -70.866667,
        "timezone_integer": 4,
        "timezone": "America/Caracas",
        "diameter": 1,
        "elevation": 3610,
        "light_pollution": 5,
    },
    {
        "name": "Laboratorio Nacional de Astrofisica, Brazil",
        "latitude": -22.534444,
        "longitude": -45.582500,
        "timezone_integer": 3,
        "timezone": "America/Sao_Paulo",
        "diameter": 1.6,
        "elevation": 1847,
        "light_pollution": 7,
    },
    {
        "name": "Complejo Astronomico El Leoncito, San Juan, Argentina",
        "latitude": -31.799167,
        "longitude": -69.295000,
        "timezone_integer": 3,
        "timezone": "America/Argentina/San_Juan",
        "diameter": 2.2,
        "elevation": 2482,
        "light_pollution": 2,
    },
    {
        "name": "Mt. Stromlo Observatory",
        "latitude": -35.320650,
        "longitude": 149.0081,
        "timezone_integer": -10,
        "timezone": "Australia/Sydney",
        "diameter": 0.2286,
        "elevation": 767,
        "light_pollution": 9,
    },
    {
        "name": "Mt. Kent Observatory",
        "latitude": -27.797861,
        "longitude": 151.855417,
        "timezone": "Australia/Brisbane",
        "diameter": 0.7,
        "elevation": 671,
        "light_pollution": 2,
    },
    {
        "name": "Anglo-Australian Observatory / Siding Spring",
        "latitude": -31.274,
        "longitude": 149.069,
        "timezone_integer": -10,
        "timezone": "Australia/Sydney",
        "diameter": 3.89,
        "elevation": 1136,
        "light_pollution": 0,
    },
    {
        "name": "Mount John University Observatory, New Zealand",
        "latitude": -43.986667,
        "longitude": 170.465,
        "timezone_integer": -12,
        "timezone": "Pacific/Auckland",
        "diameter": 1.8,
        "elevation": 1028,
        "light_pollution": 2,
    },
    {
        "name": "Roque de los Muchachos, La Palma",
        "latitude": 28.758333,
        "longitude": -17.880000,
        "timezone_integer": 0,
        "timezone": "Atlantic/Canary",
        "diameter": 10.4,
        "elevation": 2270,
        "light_pollution": 3,
    },
    {
        "name": "Observatorio de Sierra Nevada, Spain",
        "latitude": 37.064167,
        "longitude": -3.384722,
        "timezone_integer": -1,
        "timezone": "Europe/Madrid",
        "diameter": 1.5,
        "elevation": 2843,
        "light_pollution": 7,
    },
    {
        "name": "SLN - Catania Astrophysical Observatory, Italy",
        "latitude": 37.691667,
        "longitude": -345.026667,
        "timezone_integer": -1,
        "timezone": "Europe/Rome",
        "diameter": 4.3,
        "elevation": 1733,
        "light_pollution": 9,
    },
    {
        "name": "Mt. Ekar Observatory, Asiago, Italy",
        "latitude": 45.848589,
        "longitude": -348.418867,
        "timezone_integer": -1,
        "timezone": "Europe/Rome",
        "diameter": 1.22,
        "elevation": 1413,
        "light_pollution": 9,
    },
    {
        "name": "Ege University Observatory, Izmir, Turkey",
        "latitude": 38.398333,
        "longitude": 27.275000,
        "timezone_integer": 2,
        "timezone": "Europe/Istanbul",
        "diameter": 0.48,
        "elevation": 770,
        "light_pollution": 10,
    },
    {
        "name": "Tubitak National Observatory, Turkey",
        "latitude": 36.825000,
        "longitude": 30.333333,
        "timezone_integer": -2,
        "timezone": "Europe/Istanbul",
        "diameter": 1.5,
        "elevation": 2457,
        "light_pollution": 7,
    },
    {
        "name": "National Astronomical Observatory Rozhen - Bulgaria",
        "latitude": 41.693056,
        "longitude": -335.256111,
        "timezone_integer": -2,
        "timezone": "Europe/Sofia",
        "diameter": 2,
        "elevation": 1732,
        "light_pollution": 5,
    },
    {
        "name": "Calar Alto Observatory, Spain",
        "latitude": 37.223611,
        "longitude": -2.546250,
        "timezone_integer": -1,
        "timezone": "Europe/Madrid",
        "diameter": 3.5,
        "elevation": 2158,
        "light_pollution": 5,
    },
    {
        "name": "Observatorium Hoher List (Universität Bonn) - Germany",
        "latitude": 50.162760,
        "longitude": 6.850000,
        "timezone_integer": -1,
        "timezone": "Europe/Berlin",
        "diameter": 0.5,
        "elevation": 503,
        "light_pollution": 6,
    },
    {
        "name": "Boyden Observatory, Bloemfontein, South Africa",
        "latitude": -29.038889,
        "longitude": -332.594444,
        "timezone_integer": -2,
        "timezone": "Africa/Johannesburg",
        "diameter": 1.5,
        "elevation": 1372,
        "light_pollution": 0,
    },
    {
        "name": "South African Astronomical Observatory",
        "latitude": -32.379444,
        "longitude": -339.189306,
        "timezone_integer": -2,
        "timezone": "Africa/Johannesburg",
        "diameter": 9.2,
        "elevation": 1798,
        "light_pollution": 0,
    },
    {
        "name": "Beijing XingLong Observatory, China",
        "latitude": 40.393333,
        "longitude": -242.425000,
        "timezone_integer": -8,
        "timezone": "Asia/Shanghai",
        "diameter": 2.16,
        "elevation": 950,
        "light_pollution": 7,
    },
    {
        "name": "Vainu Bappu Observatory, India",
        "latitude": 12.576660,
        "longitude": -281.173400,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
        "diameter": 2.34,
        "elevation": 725,
        "light_pollution": 6,
    },
    {
        "name": "Indian Astronomical Observatory, Hanle",
        "latitude": 32.779400,
        "longitude": -281.035830,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
        "diameter": 2,
        "elevation": 4486,
        "light_pollution": 1,
    },
    {
        "name": "Aryabhatta Research Institute, India",
        "latitude": 29.360000,
        "longitude": -280.543610,
        "timezone_integer": -5,
        "timezone": "Asia/Kolkata",
        "diameter": 3.6,
        "elevation": 2398,
        "light_pollution": 5,
    },
]